name: football_betting_de
version: 1.0.0
config-version: 2

profile: football_betting_de

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"

models:
  football_betting_de:
    staging:
      +materialized: view
    silver:
      +materialized: view
    marts:
      +materialized: view
