football_betting_de:
  target: dev
  outputs:
    dev:
      type: dremio
      software_host: "{{ env_var('DREMIO_HOST', 'localhost') }}"
      port: "{{ env_var('DREMIO_PORT', '9047') | int }}"
      user: "{{ env_var('DREMIO_USER', 'admin') }}"
      password: "{{ env_var('DREMIO_PASSWORD', 'admin12345') }}"
      use_ssl: false
      verify_ssl: false
      object_storage_source: "$scratch"
      object_storage_path: "no_schema"
      dremio_space: "semantic"
      dremio_space_folder: "no_schema"
