version: 2

sources:
  - name: semantic
    database: semantic
    schema: no_schema
    tables:
      - name: raw_matches_odds
      - name: pipeline_run
      - name: file_manifest
      - name: dim_league
