#!/usr/bin/env python3
"""Generate football betting picks and accumulator combinations from historical data."""

from __future__ import annotations

import argparse
import itertools
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

try:
    from sports_betting.team_names import canonical_team_name
except ModuleNotFoundError:
    from team_names import canonical_team_name

RESULT_VALUES = {"H", "D", "A"}
OUTCOME_ORDER = ("H", "D", "A")
OUTCOME_LABEL = {"H": "1", "D": "X", "A": "2"}
OUTCOME_NAME = {"H": "home_win", "D": "draw", "A": "away_win"}

ODDS_COLUMNS = {
    "avg": {"H": "odds_avg_home", "D": "odds_avg_draw", "A": "odds_avg_away"},
    "max": {"H": "odds_max_home", "D": "odds_max_draw", "A": "odds_max_away"},
    "b365": {"H": "odds_b365_home", "D": "odds_b365_draw", "A": "odds_b365_away"},
    "pinnacle": {
        "H": "odds_pinnacle_home",
        "D": "odds_pinnacle_draw",
        "A": "odds_pinnacle_away",
    },
}

STAT_COLUMNS = [
    "home_goals_ft",
    "away_goals_ft",
    "home_shots",
    "away_shots",
    "home_shots_on_target",
    "away_shots_on_target",
    "home_fouls",
    "away_fouls",
    "home_corners",
    "away_corners",
    "home_yellow_cards",
    "away_yellow_cards",
    "home_red_cards",
    "away_red_cards",
]


@dataclass(frozen=True)
class LeaguePrior:
    home_rate: float
    draw_rate: float
    away_rate: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build betting picks (1X2) and accumulator combinations for upcoming matches."
        )
    )
    parser.add_argument(
        "--data-file",
        type=Path,
        default=Path("data/sports/processed/top6_plus_portugal_matches_odds_since2022.csv"),
        help="Processed CSV file generated by fetch_top6_data.py.",
    )
    parser.add_argument(
        "--as-of-date",
        type=str,
        default=date.today().isoformat(),
        help="Date used as training cut-off (YYYY-MM-DD).",
    )
    parser.add_argument(
        "--start-date",
        type=str,
        default=date.today().isoformat(),
        help="First fixture date to consider for suggested bets (YYYY-MM-DD).",
    )
    parser.add_argument(
        "--days-ahead",
        type=int,
        default=3,
        help="Number of days after start-date to include fixtures.",
    )
    parser.add_argument(
        "--include-completed-fixtures",
        action="store_true",
        help="Use fixtures with known results in the selected date range (backtest/demo mode).",
    )
    parser.add_argument(
        "--combo-sizes",
        type=str,
        default="2,3",
        help="Comma-separated accumulator sizes (example: 2,3,4).",
    )
    parser.add_argument(
        "--num-combos",
        type=int,
        default=20,
        help="Maximum number of combinations returned per combo size.",
    )
    parser.add_argument(
        "--max-picks-pool",
        type=int,
        default=24,
        help="Top N picks used to build combinations.",
    )
    parser.add_argument(
        "--odds-source",
        choices=("auto", "avg", "max", "b365", "pinnacle"),
        default="auto",
        help="Odds source used for scoring picks.",
    )
    parser.add_argument(
        "--min-pick-prob",
        type=float,
        default=0.28,
        help="Minimum model probability for a single pick.",
    )
    parser.add_argument(
        "--min-pick-ev",
        type=float,
        default=0.03,
        help="Minimum expected ROI for a single pick.",
    )
    parser.add_argument(
        "--min-combo-ev",
        type=float,
        default=0.05,
        help="Minimum expected ROI for a combination.",
    )
    parser.add_argument(
        "--momentum-window",
        type=int,
        default=5,
        help="How many recent matches are used for momentum/form features.",
    )
    parser.add_argument(
        "--h2h-years",
        type=int,
        default=20,
        help="Head-to-head lookback window in years (recency-weighted).",
    )
    parser.add_argument(
        "--injuries-file",
        type=Path,
        default=Path("data/sports/external/injuries.csv"),
        help="Optional injuries CSV (team-level impact adjustment).",
    )
    parser.add_argument(
        "--player-contrib-file",
        type=Path,
        default=Path("data/sports/external/player_contributions.csv"),
        help="Optional player contributions CSV (last-game impact adjustment).",
    )
    parser.add_argument(
        "--other-competitions-file",
        type=Path,
        default=Path("data/sports/external/other_competitions_matches.csv"),
        help="Optional matches CSV from other competitions (congestion signal).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/sports/outputs"),
        help="Directory where picks and combinations are saved.",
    )
    return parser.parse_args()


def parse_date(value: str) -> pd.Timestamp:
    parsed = pd.to_datetime(value, errors="coerce")
    if pd.isna(parsed):
        raise ValueError(f"Invalid date: {value!r}. Use YYYY-MM-DD format.")
    return pd.Timestamp(parsed.date())


def parse_combo_sizes(value: str) -> list[int]:
    sizes: list[int] = []
    for part in value.split(","):
        stripped = part.strip()
        if not stripped:
            continue
        size = int(stripped)
        if size < 2:
            raise ValueError("Combination sizes must be >= 2.")
        sizes.append(size)
    if not sizes:
        raise ValueError("At least one combo size is required.")
    return sorted(set(sizes))


def _read_optional_csv(path: Path, required_cols: list[str]) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    try:
        df = pd.read_csv(path)
    except Exception:
        return pd.DataFrame()
    if any(col not in df.columns for col in required_cols):
        return pd.DataFrame()
    for col in ("team", "team_name", "club", "home_team", "away_team"):
        if col in df.columns:
            df[col] = df[col].map(canonical_team_name)
    return df


def load_data(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    if "match_date" not in df.columns:
        raise ValueError("CSV missing required column: match_date")
    df["match_date"] = pd.to_datetime(df["match_date"], errors="coerce")
    df = df.loc[df["match_date"].notna()].copy()
    if "home_team" in df.columns:
        df["home_team"] = df["home_team"].map(canonical_team_name)
    if "away_team" in df.columns:
        df["away_team"] = df["away_team"].map(canonical_team_name)

    for col in STAT_COLUMNS:
        if col not in df.columns:
            df[col] = np.nan
        df[col] = pd.to_numeric(df[col], errors="coerce")
    return df


def league_priors(historical: pd.DataFrame) -> dict[str, LeaguePrior]:
    priors: dict[str, LeaguePrior] = {}
    grouped = historical.groupby("league_code", dropna=False)
    for league_code, chunk in grouped:
        total = max(len(chunk), 1)
        home_rate = float((chunk["result_ft"] == "H").sum()) / total
        draw_rate = float((chunk["result_ft"] == "D").sum()) / total
        away_rate = float((chunk["result_ft"] == "A").sum()) / total
        priors[str(league_code)] = LeaguePrior(home_rate, draw_rate, away_rate)
    if not priors:
        priors["global"] = LeaguePrior(0.44, 0.25, 0.31)
    return priors


def _prepare_team_match_rows(historical: pd.DataFrame) -> pd.DataFrame:
    base = historical.copy()
    for col in STAT_COLUMNS:
        base[col] = pd.to_numeric(base[col], errors="coerce").fillna(0.0)

    home = pd.DataFrame(
        {
            "match_date": base["match_date"],
            "league_code": base["league_code"],
            "team": base["home_team"],
            "is_home": 1,
            "points": np.where(base["result_ft"] == "H", 3, np.where(base["result_ft"] == "D", 1, 0)),
            "draw": (base["result_ft"] == "D").astype(int),
            "goals_for": base["home_goals_ft"],
            "goals_against": base["away_goals_ft"],
            "shots_for": base["home_shots"],
            "shots_against": base["away_shots"],
            "sot_for": base["home_shots_on_target"],
            "sot_against": base["away_shots_on_target"],
            "fouls": base["home_fouls"],
            "corners_for": base["home_corners"],
            "corners_against": base["away_corners"],
            "yellow": base["home_yellow_cards"],
            "red": base["home_red_cards"],
        }
    )

    away = pd.DataFrame(
        {
            "match_date": base["match_date"],
            "league_code": base["league_code"],
            "team": base["away_team"],
            "is_home": 0,
            "points": np.where(base["result_ft"] == "A", 3, np.where(base["result_ft"] == "D", 1, 0)),
            "draw": (base["result_ft"] == "D").astype(int),
            "goals_for": base["away_goals_ft"],
            "goals_against": base["home_goals_ft"],
            "shots_for": base["away_shots"],
            "shots_against": base["home_shots"],
            "sot_for": base["away_shots_on_target"],
            "sot_against": base["home_shots_on_target"],
            "fouls": base["away_fouls"],
            "corners_for": base["away_corners"],
            "corners_against": base["home_corners"],
            "yellow": base["away_yellow_cards"],
            "red": base["away_red_cards"],
        }
    )

    team_rows = pd.concat([home, away], ignore_index=True)
    team_rows["goal_diff"] = team_rows["goals_for"] - team_rows["goals_against"]
    team_rows["corners_diff"] = team_rows["corners_for"] - team_rows["corners_against"]
    team_rows["cards_weighted"] = team_rows["yellow"] + 2.0 * team_rows["red"]
    team_rows = team_rows.sort_values(["league_code", "team", "match_date"]).reset_index(drop=True)
    return team_rows


def _momentum_slope_from_series(points_series: "pd.Series") -> float:  # noqa: F821
    """OLS slope of a points sequence normalised by max-points-per-game (3).

    Positive = improving form; negative = declining form.
    Returns 0.0 if fewer than 2 observations.
    """
    import numpy as _np  # local import to keep module-level namespace clean
    vals = list(points_series)
    n = len(vals)
    if n < 2:
        return 0.0
    x = _np.arange(n, dtype=float)
    y = _np.array(vals, dtype=float)
    x_mean = x.mean()
    y_mean = y.mean()
    denom = float(_np.sum((x - x_mean) ** 2))
    if denom <= 0.0:
        return 0.0
    slope = float(_np.sum((x - x_mean) * (y - y_mean))) / denom
    return slope / 3.0  # normalise: WWWWW ≈ +0.9, LLLLL ≈ -0.9


def _last_n_features(team_rows: pd.DataFrame, window: int) -> pd.DataFrame:
    recs: list[dict[str, float | str]] = []
    for (league_code, team), g in team_rows.groupby(["league_code", "team"], dropna=False):
        tail = g.tail(window)
        if tail.empty:
            continue
        # Shots-on-target differential: sot_for - sot_against (proxy for xG)
        sot_diff_pg = float((tail["sot_for"] - tail["sot_against"]).mean()) if "sot_for" in tail.columns else 0.0
        recs.append(
            {
                "league_code": league_code,
                "team": team,
                "last_points_pg": float(tail["points"].mean()),
                "last_goal_diff_pg": float(tail["goal_diff"].mean()),
                "last_goals_for_pg": float(tail["goals_for"].mean()),
                "last_goals_against_pg": float(tail["goals_against"].mean()),
                "last_corners_diff_pg": float(tail["corners_diff"].mean()),
                "last_cards_pg": float(tail["cards_weighted"].mean()),
                "last_draw_rate": float(tail["draw"].mean()),
                # ── NEW v2 features ──────────────────────────────────────────
                "last_sot_diff_pg": sot_diff_pg,
                "last_momentum_slope": _momentum_slope_from_series(tail["points"]),
            }
        )
    return pd.DataFrame(recs)


def _team_aggregates(team_rows: pd.DataFrame, as_of_date: pd.Timestamp) -> pd.DataFrame:
    overall = (
        team_rows.groupby(["league_code", "team"], dropna=False)
        .agg(
            matches=("points", "size"),
            points=("points", "sum"),
            goals_for=("goals_for", "sum"),
            goals_against=("goals_against", "sum"),
            goal_diff=("goal_diff", "sum"),
            draw_rate=("draw", "mean"),
            cards_pg=("cards_weighted", "mean"),
            corners_diff_pg=("corners_diff", "mean"),
            sot_diff_pg=("sot_for", lambda x: float(x.mean()) if len(x) else 0.0),
            sot_against_pg=("sot_against", "mean"),
            last_match_date=("match_date", "max"),
        )
        .reset_index()
    )

    home_ppg = (
        team_rows.loc[team_rows["is_home"] == 1]
        .groupby(["league_code", "team"], dropna=False)["points"]
        .mean()
        .rename("home_ppg")
        .reset_index()
    )
    away_ppg = (
        team_rows.loc[team_rows["is_home"] == 0]
        .groupby(["league_code", "team"], dropna=False)["points"]
        .mean()
        .rename("away_ppg")
        .reset_index()
    )

    seven_days_ago = as_of_date - pd.Timedelta(days=7)
    matches_last7 = (
        team_rows.loc[team_rows["match_date"] >= seven_days_ago]
        .groupby(["league_code", "team"], dropna=False)
        .size()
        .rename("league_matches_last7")
        .reset_index()
    )

    agg = overall.merge(home_ppg, on=["league_code", "team"], how="left")
    agg = agg.merge(away_ppg, on=["league_code", "team"], how="left")
    agg = agg.merge(matches_last7, on=["league_code", "team"], how="left")

    agg["home_ppg"] = agg["home_ppg"].fillna(0.0)
    agg["away_ppg"] = agg["away_ppg"].fillna(0.0)
    agg["league_matches_last7"] = agg["league_matches_last7"].fillna(0.0)
    agg["goals_for_pg"] = agg["goals_for"] / agg["matches"].replace(0, np.nan)
    agg["goals_against_pg"] = agg["goals_against"] / agg["matches"].replace(0, np.nan)
    agg["goal_diff_pg"] = agg["goal_diff"] / agg["matches"].replace(0, np.nan)
    agg["goals_for_pg"] = agg["goals_for_pg"].fillna(0.0)
    agg["goals_against_pg"] = agg["goals_against_pg"].fillna(0.0)
    agg["goal_diff_pg"] = agg["goal_diff_pg"].fillna(0.0)
    agg["days_rest"] = (as_of_date - pd.to_datetime(agg["last_match_date"])).dt.days
    agg["days_rest"] = agg["days_rest"].fillna(14).clip(lower=0)
    return agg


def _league_positions(team_snapshot: pd.DataFrame) -> pd.DataFrame:
    ranked = team_snapshot.copy()
    ranked["position"] = (
        ranked.sort_values(["league_code", "points", "goal_diff", "goals_for"], ascending=[True, False, False, False])
        .groupby("league_code")
        .cumcount()
        + 1
    )
    return ranked


def _extract_importance_col(df: pd.DataFrame) -> str | None:
    for col in ("importance", "impact", "importance_score", "player_importance", "weight"):
        if col in df.columns:
            return col
    return None


def _extract_team_col(df: pd.DataFrame) -> str | None:
    for col in ("team", "team_name", "club"):
        if col in df.columns:
            return col
    return None


def _extract_player_col(df: pd.DataFrame) -> str | None:
    for col in ("player", "player_name", "name"):
        if col in df.columns:
            return col
    return None


def build_injury_snapshot(injuries_df: pd.DataFrame, as_of_date: pd.Timestamp) -> pd.DataFrame:
    if injuries_df.empty:
        return pd.DataFrame(columns=["team", "injury_count", "injury_impact"])

    team_col = _extract_team_col(injuries_df)
    if team_col is None:
        return pd.DataFrame(columns=["team", "injury_count", "injury_impact"])

    date_col = "date" if "date" in injuries_df.columns else "report_date" if "report_date" in injuries_df.columns else None
    if date_col is None:
        return pd.DataFrame(columns=["team", "injury_count", "injury_impact"])

    injuries = injuries_df.copy()
    injuries[date_col] = pd.to_datetime(injuries[date_col], errors="coerce")
    injuries = injuries.loc[injuries[date_col].notna() & (injuries[date_col] <= as_of_date)].copy()

    if "expected_return" in injuries.columns:
        injuries["expected_return"] = pd.to_datetime(injuries["expected_return"], errors="coerce")
        injuries = injuries.loc[
            injuries["expected_return"].isna() | (injuries["expected_return"] >= as_of_date)
        ].copy()

    if "status" in injuries.columns:
        status = injuries["status"].astype(str).str.lower()
        allowed = status.str.contains("out|inj|doubt|suspend", na=False)
        injuries = injuries.loc[allowed].copy()

    importance_col = _extract_importance_col(injuries)
    if importance_col is None:
        injuries["injury_importance"] = 1.0
    else:
        injuries["injury_importance"] = pd.to_numeric(injuries[importance_col], errors="coerce").fillna(1.0)

    injuries = injuries.rename(columns={team_col: "team"})
    return (
        injuries.groupby("team", dropna=False)
        .agg(injury_count=("team", "size"), injury_impact=("injury_importance", "sum"))
        .reset_index()
    )


def build_player_contrib_snapshot(contrib_df: pd.DataFrame, as_of_date: pd.Timestamp) -> pd.DataFrame:
    if contrib_df.empty:
        return pd.DataFrame(columns=["team", "player_form", "last_game_key_players"])

    team_col = _extract_team_col(contrib_df)
    if team_col is None or "match_date" not in contrib_df.columns:
        return pd.DataFrame(columns=["team", "player_form", "last_game_key_players"])

    contrib = contrib_df.copy()
    contrib["match_date"] = pd.to_datetime(contrib["match_date"], errors="coerce")
    contrib = contrib.loc[contrib["match_date"].notna() & (contrib["match_date"] <= as_of_date)].copy()
    if contrib.empty:
        return pd.DataFrame(columns=["team", "player_form", "last_game_key_players"])

    for c in ("goals", "assists", "xg", "xa", "key_passes", "minutes", "rating"):
        if c not in contrib.columns:
            contrib[c] = 0.0
        contrib[c] = pd.to_numeric(contrib[c], errors="coerce").fillna(0.0)

    contrib["impact"] = (
        1.3 * contrib["goals"]
        + 1.0 * contrib["assists"]
        + 0.7 * contrib["xg"]
        + 0.5 * contrib["xa"]
        + 0.08 * contrib["key_passes"]
        + 0.02 * contrib["minutes"]
        + 0.2 * contrib["rating"]
    )

    contrib = contrib.rename(columns={team_col: "team"})
    latest_date = contrib.groupby("team", dropna=False)["match_date"].max().rename("latest_date")
    latest = contrib.merge(latest_date, on="team", how="left")
    latest = latest.loc[latest["match_date"] == latest["latest_date"]].copy()

    return (
        latest.groupby("team", dropna=False)
        .agg(
            player_form=("impact", "sum"),
            last_game_key_players=("impact", lambda x: float((x > 1.2).sum())),
        )
        .reset_index()
    )


def build_other_comp_snapshot(other_df: pd.DataFrame, as_of_date: pd.Timestamp) -> pd.DataFrame:
    if other_df.empty:
        return pd.DataFrame(columns=["team", "other_matches_last7", "other_days_rest"])

    team_col = _extract_team_col(other_df)
    date_col = "match_date" if "match_date" in other_df.columns else "date" if "date" in other_df.columns else None
    if team_col is None or date_col is None:
        return pd.DataFrame(columns=["team", "other_matches_last7", "other_days_rest"])

    other = other_df.copy()
    other[date_col] = pd.to_datetime(other[date_col], errors="coerce")
    other = other.loc[other[date_col].notna() & (other[date_col] <= as_of_date)].copy()
    if other.empty:
        return pd.DataFrame(columns=["team", "other_matches_last7", "other_days_rest"])

    seven_days_ago = as_of_date - pd.Timedelta(days=7)
    last7 = (
        other.loc[other[date_col] >= seven_days_ago]
        .groupby(team_col, dropna=False)
        .size()
        .rename("other_matches_last7")
        .reset_index()
        .rename(columns={team_col: "team"})
    )
    last_date = (
        other.groupby(team_col, dropna=False)[date_col]
        .max()
        .rename("other_last_match")
        .reset_index()
        .rename(columns={team_col: "team"})
    )

    snapshot = last7.merge(last_date, on="team", how="outer")
    snapshot["other_matches_last7"] = snapshot["other_matches_last7"].fillna(0.0)
    snapshot["other_days_rest"] = (as_of_date - pd.to_datetime(snapshot["other_last_match"])).dt.days
    snapshot["other_days_rest"] = snapshot["other_days_rest"].fillna(14).clip(lower=0)
    return snapshot[["team", "other_matches_last7", "other_days_rest"]]


def h2h_features_for_match(
    historical: pd.DataFrame,
    league_code: str,
    home_team: str,
    away_team: str,
    as_of_date: pd.Timestamp,
    years: int,
    half_life_days: float = 900.0,
) -> dict[str, float]:
    min_date = as_of_date - pd.Timedelta(days=max(years, 1) * 365)
    h2h = historical.loc[
        (historical["league_code"] == league_code)
        & (historical["match_date"] >= min_date)
        & (
            ((historical["home_team"] == home_team) & (historical["away_team"] == away_team))
            | ((historical["home_team"] == away_team) & (historical["away_team"] == home_team))
        )
    ].copy()
    if h2h.empty:
        return {
            "h2h_matches": 0.0,
            "h2h_home_win_rate": 0.0,
            "h2h_draw_rate": 0.0,
            "h2h_away_win_rate": 0.0,
            "h2h_goal_diff_pg": 0.0,
            "h2h_gap": 0.0,
        }

    h2h["match_date"] = pd.to_datetime(h2h["match_date"], errors="coerce")
    ages = (as_of_date - h2h["match_date"]).dt.days.clip(lower=0)
    weights = np.exp(-ages / max(half_life_days, 1.0))

    same_orientation = (h2h["home_team"] == home_team) & (h2h["away_team"] == away_team)
    home_goals = pd.to_numeric(h2h["home_goals_ft"], errors="coerce").fillna(0.0)
    away_goals = pd.to_numeric(h2h["away_goals_ft"], errors="coerce").fillna(0.0)
    perspective_goal_diff = np.where(
        same_orientation,
        home_goals - away_goals,
        away_goals - home_goals,
    )

    result = h2h["result_ft"].astype(str)
    perspective_result = np.where(
        same_orientation,
        result,
        np.where(result == "H", "A", np.where(result == "A", "H", "D")),
    )

    total_w = float(weights.sum())
    if total_w <= 0:
        total_w = 1.0
    home_w = float(weights[perspective_result == "H"].sum()) / total_w
    draw_w = float(weights[perspective_result == "D"].sum()) / total_w
    away_w = float(weights[perspective_result == "A"].sum()) / total_w
    goal_diff_w = float(np.sum(perspective_goal_diff * weights) / total_w)

    return {
        "h2h_matches": float(len(h2h)),
        "h2h_home_win_rate": float(home_w),
        "h2h_draw_rate": float(draw_w),
        "h2h_away_win_rate": float(away_w),
        "h2h_goal_diff_pg": float(goal_diff_w),
        "h2h_gap": float(home_w - away_w),
    }


def _active_injuries_table(injuries_df: pd.DataFrame, as_of_date: pd.Timestamp) -> pd.DataFrame:
    if injuries_df.empty:
        return pd.DataFrame()
    team_col = _extract_team_col(injuries_df)
    date_col = "date" if "date" in injuries_df.columns else "report_date" if "report_date" in injuries_df.columns else None
    if team_col is None or date_col is None:
        return pd.DataFrame()

    injuries = injuries_df.copy()
    injuries[date_col] = pd.to_datetime(injuries[date_col], errors="coerce")
    injuries = injuries.loc[injuries[date_col].notna() & (injuries[date_col] <= as_of_date)].copy()
    if "expected_return" in injuries.columns:
        injuries["expected_return"] = pd.to_datetime(injuries["expected_return"], errors="coerce")
        injuries = injuries.loc[
            injuries["expected_return"].isna() | (injuries["expected_return"] >= as_of_date)
        ].copy()
    if "status" in injuries.columns:
        status = injuries["status"].astype(str).str.lower()
        injuries = injuries.loc[status.str.contains("out|inj|doubt|suspend", na=False)].copy()

    player_col = _extract_player_col(injuries) or "player"
    if player_col not in injuries.columns:
        injuries[player_col] = "Unknown"
    importance_col = _extract_importance_col(injuries)
    if importance_col is None:
        injuries["importance_score"] = 1.0
    else:
        injuries["importance_score"] = pd.to_numeric(
            injuries[importance_col], errors="coerce"
        ).fillna(1.0)

    injuries = injuries.rename(
        columns={team_col: "team", player_col: "player", date_col: "date"}
    )
    if "status" not in injuries.columns:
        injuries["status"] = "injured"
    if "expected_return" not in injuries.columns:
        injuries["expected_return"] = pd.NaT
    return injuries[
        ["team", "player", "status", "importance_score", "date", "expected_return"]
    ].copy()


def player_match_insights(
    home_team: str,
    away_team: str,
    as_of_date: pd.Timestamp,
    injuries_df: pd.DataFrame,
    contrib_df: pd.DataFrame,
    top_n: int = 5,
    player_stats_df: pd.DataFrame | None = None,
) -> dict[str, pd.DataFrame]:
    target_teams = {home_team, away_team}

    injured = _active_injuries_table(injuries_df, as_of_date)
    if injured.empty:
        injured_out = pd.DataFrame(
            columns=["team", "player", "status", "importance_score", "expected_return"]
        )
    else:
        injured_out = (
            injured.loc[injured["team"].isin(target_teams)]
            .sort_values(["importance_score", "date"], ascending=[False, False])
            .head(max(top_n * 2, 6))
            .reset_index(drop=True)
        )
        injured_out["expected_return"] = pd.to_datetime(
            injured_out["expected_return"], errors="coerce"
        ).dt.date

    if contrib_df.empty:
        # Fallback: derive likely scorers from season player stats when per-match
        # contrib data is unavailable.
        scorers_fallback = pd.DataFrame(columns=["team", "player", "score_likelihood"])
        if player_stats_df is not None and not player_stats_df.empty:
            _ps = player_stats_df.copy()
            _tc = "team" if "team" in _ps.columns else None
            _pc = "player" if "player" in _ps.columns else "player_name" if "player_name" in _ps.columns else None
            if _tc and _pc:
                _ps = _ps.loc[_ps[_tc].isin({home_team, away_team})].copy()
                for c in ("goals", "assists", "xg", "xa", "key_passes", "minutes"):
                    if c not in _ps.columns:
                        _ps[c] = 0.0
                    _ps[c] = pd.to_numeric(_ps[c], errors="coerce").fillna(0.0)
                _min90 = (_ps["minutes"] / 90.0).clip(lower=0.5)
                _ps["score_likelihood"] = (
                    1.5 * _ps["goals"]
                    + 0.8 * _ps["xg"]
                    + 0.5 * _ps["assists"]
                    + 0.3 * _ps.get("key_passes", 0.0)
                ) / _min90
                _injured_names = set(injured_out["player"].astype(str)) if not injured_out.empty else set()
                _ps = _ps.loc[~_ps[_pc].astype(str).isin(_injured_names)]
                scorers_fallback = (
                    _ps.sort_values("score_likelihood", ascending=False)
                    .head(max(top_n, 1))
                    .rename(columns={_tc: "team", _pc: "player"})[["team", "player", "score_likelihood"]]
                    .reset_index(drop=True)
                )
        return {
            "injured_players": injured_out,
            "likely_scorers": scorers_fallback,
            "likely_cards": pd.DataFrame(columns=["team", "player", "card_likelihood"]),
        }

    team_col = _extract_team_col(contrib_df)
    player_col = _extract_player_col(contrib_df)
    if team_col is None or player_col is None or "match_date" not in contrib_df.columns:
        return {
            "injured_players": injured_out,
            "likely_scorers": pd.DataFrame(columns=["team", "player", "score_likelihood"]),
            "likely_cards": pd.DataFrame(columns=["team", "player", "card_likelihood"]),
        }

    contrib = contrib_df.copy()
    contrib["match_date"] = pd.to_datetime(contrib["match_date"], errors="coerce")
    contrib = contrib.loc[
        contrib["match_date"].notna()
        & (contrib["match_date"] <= as_of_date)
        & (contrib[team_col].isin(target_teams))
    ].copy()
    if contrib.empty:
        return {
            "injured_players": injured_out,
            "likely_scorers": pd.DataFrame(columns=["team", "player", "score_likelihood"]),
            "likely_cards": pd.DataFrame(columns=["team", "player", "card_likelihood"]),
        }

    for c in ("goals", "assists", "xg", "xa", "key_passes", "shots_on_target", "yellow_cards", "red_cards", "fouls"):
        if c not in contrib.columns:
            contrib[c] = 0.0
        contrib[c] = pd.to_numeric(contrib[c], errors="coerce").fillna(0.0)

    days_old = (as_of_date - contrib["match_date"]).dt.days.clip(lower=0)
    recency_w = np.exp(-days_old / 120.0)
    contrib["score_signal"] = (
        1.6 * contrib["goals"]
        + 1.1 * contrib["xg"]
        + 0.6 * contrib["assists"]
        + 0.25 * contrib["shots_on_target"]
        + 0.12 * contrib["key_passes"]
    ) * recency_w
    contrib["card_signal"] = (
        1.1 * contrib["yellow_cards"] + 2.0 * contrib["red_cards"] + 0.08 * contrib["fouls"]
    ) * recency_w

    grouped = (
        contrib.groupby([team_col, player_col], dropna=False)
        .agg(score_signal=("score_signal", "sum"), card_signal=("card_signal", "sum"))
        .reset_index()
        .rename(columns={team_col: "team", player_col: "player"})
    )

    injured_names = set(injured_out["player"].astype(str)) if not injured_out.empty else set()
    available = grouped.loc[~grouped["player"].astype(str).isin(injured_names)].copy()

    scorers = (
        available.sort_values("score_signal", ascending=False)
        .head(max(top_n, 1))
        .rename(columns={"score_signal": "score_likelihood"})[["team", "player", "score_likelihood"]]
    )
    cards = (
        available.sort_values("card_signal", ascending=False)
        .head(max(top_n, 1))
        .rename(columns={"card_signal": "card_likelihood"})[["team", "player", "card_likelihood"]]
    )

    return {
        "injured_players": injured_out,
        "likely_scorers": scorers,
        "likely_cards": cards,
    }


# Yellow-card suspension thresholds per league (accumulated yellows in a season
# before a one-match ban is imposed). Most domestic leagues use 5 or 10.
# Values: (first_threshold, second_threshold) — after first_threshold the counter
# resets; we only care about the current count relative to the nearest threshold.
_YELLOW_THRESHOLDS: dict[str, int] = {
    "E0":  5,   # Premier League: 5Y → 1-match ban
    "SP1": 5,   # La Liga
    "I1":  5,   # Serie A
    "D1":  5,   # Bundesliga
    "F1":  5,   # Ligue 1
    "P1":  5,   # Primeira Liga
}
_DEFAULT_YELLOW_THRESHOLD = 5

# Importance weight assigned to a suspended player when their season impact is unknown
_UNKNOWN_SUSPENSION_WEIGHT = 1.0


def build_suspension_snapshot(
    team_rows: pd.DataFrame,
    as_of_date: pd.Timestamp,
    player_stats_df: pd.DataFrame | None = None,
) -> pd.DataFrame:
    """Estimate the number of players per team who are suspended for the next match.

    Two suspension types are detected:
    1. **Yellow-card accumulation**: a player (team-level aggregated, since we have
       team card totals not per-player cards) whose team is at or beyond the league
       suspension threshold in the current season.  We use team-level yellows as a
       proxy for how close the squad is to producing a suspension.
    2. **Red-card ban**: any match where the team received ≥1 red card implies at
       least one player misses the immediately following match.

    Returns columns: team, suspended_count, suspended_impact.
    ``suspended_impact`` is the sum of player importance scores (from player_stats_df
    if available, otherwise _UNKNOWN_SUSPENSION_WEIGHT per suspended count).
    """
    _empty = pd.DataFrame(columns=["team", "suspended_count", "suspended_impact"])
    if team_rows.empty:
        return _empty

    required = {"league_code", "team", "match_date", "yellow", "red"}
    if not required.issubset(team_rows.columns):
        return _empty

    rows = team_rows.copy()
    rows["match_date"] = pd.to_datetime(rows["match_date"], errors="coerce")
    rows = rows.loc[rows["match_date"].notna() & (rows["match_date"] <= as_of_date)].copy()
    if rows.empty:
        return _empty

    # ── Season boundary: use August cutoff matching the app convention ──────
    yr = as_of_date.year
    season_start = pd.Timestamp(yr if as_of_date.month >= 8 else yr - 1, 8, 1)
    season_rows = rows.loc[rows["match_date"] >= season_start].copy()

    records: list[dict] = []
    for (league_code, team), g in season_rows.groupby(["league_code", "team"], dropna=False):
        threshold = _YELLOW_THRESHOLDS.get(str(league_code), _DEFAULT_YELLOW_THRESHOLD)
        g_sorted = g.sort_values("match_date")

        # ── Accumulated yellow cards this season with suspension resets ──────
        running_yellows = 0
        yellow_suspensions = 0
        for _, row in g_sorted.iterrows():
            running_yellows += int(row.get("yellow", 0))
            if running_yellows >= threshold:
                yellow_suspensions += 1
                running_yellows = 0  # reset after suspension served

        # ── Red cards in the last match → player misses next match ──────────
        # Use the most recent match only (red cards from older matches are
        # assumed already served)
        last_match = g_sorted.iloc[-1] if not g_sorted.empty else None
        red_suspensions = max(0, int(last_match["red"])) if last_match is not None else 0

        # ── Total suspended players (estimated) ─────────────────────────────
        # yellow_suspensions counts how many "suspension events" the team has
        # experienced. We check whether the most recent suspension is still pending:
        # if the team played their last match after their last accumulated-yellow
        # suspension they still need to serve it for the *next* game.
        # Simplified heuristic: if team is currently AT the threshold (running_yellows
        # == threshold - 1) we flag as "at risk" (0.5 weight) rather than suspended.
        at_risk = 1 if running_yellows >= threshold - 1 else 0

        total_suspended = red_suspensions  # confirmed
        at_risk_weight = at_risk * 0.5    # probabilistic (not confirmed ban)

        records.append(
            {
                "league_code": league_code,
                "team": team,
                "suspended_count": total_suspended + at_risk_weight,
                "_reds": red_suspensions,
                "_at_risk": at_risk,
            }
        )

    if not records:
        return _empty

    df = pd.DataFrame(records)

    # ── Compute suspended_impact using player stats if available ─────────────
    # If player_stats_df has per-player stats (xg, goals, assists per 90) we can
    # estimate how impactful the suspended/at-risk players might be for each team.
    # We approximate: one suspended player costs the team their #11 player's impact.
    if player_stats_df is not None and not player_stats_df.empty:
        _ps = player_stats_df.copy()
        team_col = "team" if "team" in _ps.columns else None
        if team_col:
            for c in ("xg", "goals", "assists", "xa", "key_passes", "minutes"):
                if c not in _ps.columns:
                    _ps[c] = 0.0
                _ps[c] = pd.to_numeric(_ps[c], errors="coerce").fillna(0.0)
            _ps["_impact_p90"] = (
                1.5 * _ps["goals"]
                + 1.1 * _ps["assists"]
                + 0.8 * _ps["xg"]
                + 0.6 * _ps.get("xa", 0.0)
                + 0.10 * _ps.get("key_passes", 0.0)
            ) / (_ps["minutes"].replace(0, np.nan) / 90.0).fillna(1.0)

            # Median impact for the 11th-best player per team (proxy cost of losing one player)
            team_median_impact = (
                _ps.groupby(team_col)["_impact_p90"]
                .apply(lambda s: s.nlargest(15).iloc[-1] if len(s) >= 11 else s.median())
                .rename("_median_impact")
                .reset_index()
                .rename(columns={team_col: "team"})
            )
            df = df.merge(team_median_impact, on="team", how="left")
            df["_median_impact"] = df["_median_impact"].fillna(_UNKNOWN_SUSPENSION_WEIGHT)
            df["suspended_impact"] = df["suspended_count"] * df["_median_impact"]
        else:
            df["suspended_impact"] = df["suspended_count"] * _UNKNOWN_SUSPENSION_WEIGHT
    else:
        df["suspended_impact"] = df["suspended_count"] * _UNKNOWN_SUSPENSION_WEIGHT

    return df[["team", "suspended_count", "suspended_impact"]].copy()


def build_key_player_snapshot(player_stats_df: pd.DataFrame) -> pd.DataFrame:
    """Compute per-team squad quality score from season player stats.

    Uses gold_player_stats (xg, goals, assists, key_passes per 90) to rank
    the top 11 players per team and produce a ``key_player_impact`` score.
    This feeds the lineup_strength_gap feature even when no explicit lineup
    is entered.

    Returns columns: team, key_player_impact, top_player_name, top_player_impact.
    """
    _empty = pd.DataFrame(columns=["team", "key_player_impact", "top_player_name", "top_player_impact"])
    if player_stats_df is None or player_stats_df.empty:
        return _empty

    ps = player_stats_df.copy()
    team_col = "team" if "team" in ps.columns else None
    player_col = "player" if "player" in ps.columns else "player_name" if "player_name" in ps.columns else None
    if team_col is None or player_col is None:
        return _empty

    for c in ("xg", "goals", "assists", "xa", "key_passes", "minutes"):
        if c not in ps.columns:
            ps[c] = 0.0
        ps[c] = pd.to_numeric(ps[c], errors="coerce").fillna(0.0)

    # Per-90 weighted impact score
    ps["_min90"] = (ps["minutes"] / 90.0).clip(lower=0.5)  # at least 0.5 game equivalent
    ps["impact_p90"] = (
        1.5 * ps["goals"]
        + 1.1 * ps["assists"]
        + 0.8 * ps["xg"]
        + 0.6 * ps.get("xa", 0.0)
        + 0.10 * ps.get("key_passes", 0.0)
    ) / ps["_min90"]

    records: list[dict] = []
    for team, g in ps.groupby(team_col, dropna=False):
        top11 = g.nlargest(11, "impact_p90")
        if top11.empty:
            continue
        top1 = top11.iloc[0]
        records.append(
            {
                "team": team,
                "key_player_impact": float(top11["impact_p90"].mean()),
                "top_player_name": str(top1[player_col]),
                "top_player_impact": float(top1["impact_p90"]),
            }
        )

    if not records:
        return _empty
    return pd.DataFrame(records)


def build_team_snapshot(
    historical: pd.DataFrame,
    as_of_date: pd.Timestamp,
    momentum_window: int,
    injuries_df: pd.DataFrame,
    player_contrib_df: pd.DataFrame,
    other_comp_df: pd.DataFrame,
    player_stats_df: pd.DataFrame | None = None,
) -> pd.DataFrame:
    team_rows = _prepare_team_match_rows(historical)
    aggregate = _team_aggregates(team_rows, as_of_date)
    recent = _last_n_features(team_rows, window=momentum_window)
    snapshot = aggregate.merge(recent, on=["league_code", "team"], how="left")

    injury_snapshot = build_injury_snapshot(injuries_df, as_of_date)
    contrib_snapshot = build_player_contrib_snapshot(player_contrib_df, as_of_date)
    other_snapshot = build_other_comp_snapshot(other_comp_df, as_of_date)
    suspension_snapshot = build_suspension_snapshot(team_rows, as_of_date, player_stats_df)
    key_player_snapshot = build_key_player_snapshot(player_stats_df if player_stats_df is not None else pd.DataFrame())

    snapshot = snapshot.merge(injury_snapshot, on="team", how="left")
    snapshot = snapshot.merge(contrib_snapshot, on="team", how="left")
    snapshot = snapshot.merge(other_snapshot, on="team", how="left")
    snapshot = snapshot.merge(suspension_snapshot, on="team", how="left")
    snapshot = snapshot.merge(key_player_snapshot, on="team", how="left")

    fill_zero = [
        "last_points_pg",
        "last_goal_diff_pg",
        "last_goals_for_pg",
        "last_goals_against_pg",
        "last_corners_diff_pg",
        "last_cards_pg",
        "last_draw_rate",
        "last_sot_diff_pg",
        "last_momentum_slope",
        "injury_count",
        "injury_impact",
        "player_form",
        "last_game_key_players",
        "other_matches_last7",
        "suspended_count",
        "suspended_impact",
        "key_player_impact",
        "top_player_impact",
    ]
    for col in fill_zero:
        snapshot[col] = pd.to_numeric(snapshot[col], errors="coerce").fillna(0.0)

    if "top_player_name" not in snapshot.columns:
        snapshot["top_player_name"] = ""
    snapshot["top_player_name"] = snapshot["top_player_name"].fillna("")

    if "other_days_rest" not in snapshot.columns:
        snapshot["other_days_rest"] = 14.0
    snapshot["other_days_rest"] = pd.to_numeric(
        snapshot["other_days_rest"], errors="coerce"
    ).fillna(14.0)

    snapshot["total_matches_last7"] = snapshot["league_matches_last7"] + snapshot["other_matches_last7"]
    snapshot["days_rest_effective"] = snapshot[["days_rest", "other_days_rest"]].min(axis=1)

    snapshot = _league_positions(snapshot)
    return snapshot


def _lookup_team_snapshot(snapshot: pd.DataFrame, league_code: str, team: str) -> pd.Series:
    row = snapshot.loc[(snapshot["league_code"] == league_code) & (snapshot["team"] == team)]
    if row.empty:
        return pd.Series(dtype=float)
    return row.iloc[0]


def _squash(value: float, scale: float) -> float:
    return float(np.tanh(value / max(scale, 1e-6)))


def _weighted_score_from_features(
    home: pd.Series,
    away: pd.Series,
    h2h_gap: float,
    h2h_goal_diff_pg: float,
) -> tuple[float, dict[str, float]]:
    forward_goals_gap = (
        0.55 * float(home.get("goals_for_pg", 0.0))
        + 0.45 * float(home.get("last_goals_for_pg", 0.0))
        - 0.55 * float(away.get("goals_for_pg", 0.0))
        - 0.45 * float(away.get("last_goals_for_pg", 0.0))
    )
    features = {
        "table_rank": float(away.get("position", 10.0)) - float(home.get("position", 10.0)),
        "points_gap": float(home.get("points", 0.0)) - float(away.get("points", 0.0)),
        "momentum_gap": float(home.get("last_points_pg", 0.0)) - float(away.get("last_points_pg", 0.0)),
        "home_away_gap": float(home.get("home_ppg", 0.0)) - float(away.get("away_ppg", 0.0)),
        "forward_goals_gap": forward_goals_gap,
        "goal_diff_gap": float(home.get("goal_diff_pg", 0.0)) - float(away.get("goal_diff_pg", 0.0)),
        "defense_gap": float(away.get("goals_against_pg", 0.0)) - float(home.get("goals_against_pg", 0.0)),
        "corners_gap": float(home.get("corners_diff_pg", 0.0)) - float(away.get("corners_diff_pg", 0.0)),
        "discipline_gap": float(away.get("cards_pg", 0.0)) - float(home.get("cards_pg", 0.0)),
        "congestion_gap": float(away.get("total_matches_last7", 0.0)) - float(home.get("total_matches_last7", 0.0)),
        "rest_gap": float(home.get("days_rest_effective", 14.0)) - float(away.get("days_rest_effective", 14.0)),
        "injury_gap": float(away.get("injury_impact", 0.0)) - float(home.get("injury_impact", 0.0)),
        "player_form_gap": float(home.get("player_form", 0.0)) - float(away.get("player_form", 0.0)),
        "h2h_gap": float(h2h_gap),
        "h2h_goal_diff_gap": float(h2h_goal_diff_pg),
    }

    weights = {
        "table_rank": (0.45, 8.0),
        "points_gap": (0.30, 10.0),
        "momentum_gap": (1.10, 1.5),
        "home_away_gap": (0.95, 1.0),
        "forward_goals_gap": (0.75, 0.9),
        "goal_diff_gap": (0.80, 1.2),
        "defense_gap": (0.70, 1.0),
        "corners_gap": (0.35, 2.0),
        "discipline_gap": (0.30, 1.2),
        "congestion_gap": (0.45, 2.0),
        "rest_gap": (0.35, 4.0),
        "injury_gap": (0.70, 2.0),
        "player_form_gap": (0.25, 2.0),
        "h2h_gap": (0.60, 0.45),
        "h2h_goal_diff_gap": (0.35, 1.2),
    }

    contributions: dict[str, float] = {}
    score = 0.0
    for name, raw in features.items():
        weight, scale = weights[name]
        signed = weight * _squash(raw, scale)
        contributions[name] = signed
        score += signed
    return score, contributions


def predict_match_probs(
    row: pd.Series,
    snapshot: pd.DataFrame,
    priors: dict[str, LeaguePrior],
    h2h: dict[str, float],
) -> tuple[float, float, float, dict[str, float], str]:
    league_key = str(row["league_code"])
    prior = priors.get(league_key, priors.get("global", LeaguePrior(0.44, 0.25, 0.31)))

    home = _lookup_team_snapshot(snapshot, row["league_code"], row["home_team"])
    away = _lookup_team_snapshot(snapshot, row["league_code"], row["away_team"])

    score, contributions = _weighted_score_from_features(
        home=home,
        away=away,
        h2h_gap=float(h2h.get("h2h_gap", 0.0)),
        h2h_goal_diff_pg=float(h2h.get("h2h_goal_diff_pg", 0.0)),
    )

    draw_base = prior.draw_rate
    draw_tendency = (float(home.get("draw_rate", draw_base)) + float(away.get("draw_rate", draw_base))) / 2.0
    draw_adjust = 0.08 * _squash(draw_tendency - draw_base, 0.10) - 0.10 * abs(_squash(score, 1.5))
    p_draw = float(np.clip(draw_base + draw_adjust, 0.12, 0.38))

    remaining = 1.0 - p_draw
    home_share = 1.0 / (1.0 + float(np.exp(-score)))
    p_home = remaining * home_share
    p_away = remaining - p_home

    probs = np.array([p_home, p_draw, p_away], dtype=float)
    probs = np.maximum(probs, 1e-9)
    probs = probs / probs.sum()

    top_factors = sorted(contributions.items(), key=lambda x: abs(x[1]), reverse=True)[:3]
    explain = ", ".join(f"{k}:{v:+.2f}" for k, v in top_factors)
    return float(probs[0]), float(probs[1]), float(probs[2]), contributions, explain


def choose_odds(row: pd.Series, outcome: str, source: str) -> float | None:
    if source != "auto":
        col = ODDS_COLUMNS[source][outcome]
        value = row.get(col)
        return float(value) if pd.notna(value) and float(value) > 1.0 else None

    fallback_order = ("avg", "max", "b365", "pinnacle")
    for candidate_source in fallback_order:
        col = ODDS_COLUMNS[candidate_source][outcome]
        value = row.get(col)
        if pd.notna(value) and float(value) > 1.0:
            return float(value)
    return None


def implied_probs(odds_h: float, odds_d: float, odds_a: float) -> tuple[float, float, float]:
    inverse = np.array([1.0 / odds_h, 1.0 / odds_d, 1.0 / odds_a], dtype=float)
    probs = inverse / inverse.sum()
    return float(probs[0]), float(probs[1]), float(probs[2])


def build_pick_table(
    fixtures: pd.DataFrame,
    snapshot: pd.DataFrame,
    priors: dict[str, LeaguePrior],
    historical: pd.DataFrame,
    as_of_date: pd.Timestamp,
    h2h_years: int,
    odds_source: str,
    injuries_df: pd.DataFrame,
    contrib_df: pd.DataFrame,
) -> pd.DataFrame:
    picks: list[dict[str, object]] = []
    for _, row in fixtures.iterrows():
        h2h = h2h_features_for_match(
            historical=historical,
            league_code=str(row["league_code"]),
            home_team=str(row["home_team"]),
            away_team=str(row["away_team"]),
            as_of_date=as_of_date,
            years=max(h2h_years, 1),
        )
        p_home, p_draw, p_away, contributions, explain = predict_match_probs(
            row=row,
            snapshot=snapshot,
            priors=priors,
            h2h=h2h,
        )
        model_probs = {"H": p_home, "D": p_draw, "A": p_away}

        odds_h = choose_odds(row, "H", odds_source)
        odds_d = choose_odds(row, "D", odds_source)
        odds_a = choose_odds(row, "A", odds_source)
        if odds_h is None or odds_d is None or odds_a is None:
            continue

        imp_h, imp_d, imp_a = implied_probs(odds_h, odds_d, odds_a)
        implied = {"H": imp_h, "D": imp_d, "A": imp_a}
        odds_map = {"H": odds_h, "D": odds_d, "A": odds_a}

        home_snapshot = _lookup_team_snapshot(snapshot, row["league_code"], row["home_team"])
        away_snapshot = _lookup_team_snapshot(snapshot, row["league_code"], row["away_team"])
        insights = player_match_insights(
            home_team=str(row["home_team"]),
            away_team=str(row["away_team"]),
            as_of_date=as_of_date,
            injuries_df=injuries_df,
            contrib_df=contrib_df,
            top_n=3,
        )
        injured_list = insights["injured_players"]
        scorers = insights["likely_scorers"]
        cards = insights["likely_cards"]

        injured_summary = "; ".join(
            f"{r.team}:{r.player}({r.importance_score:.1f})"
            for r in injured_list.itertuples(index=False)
        )
        scorer_summary = "; ".join(
            f"{r.team}:{r.player}"
            for r in scorers.itertuples(index=False)
        )
        card_summary = "; ".join(
            f"{r.team}:{r.player}"
            for r in cards.itertuples(index=False)
        )

        for outcome in OUTCOME_ORDER:
            model_prob = model_probs[outcome]
            odd = odds_map[outcome]
            implied_prob = implied[outcome]
            expected_roi = model_prob * odd - 1.0
            edge = model_prob - implied_prob
            picks.append(
                {
                    "match_date": row["match_date"].date().isoformat(),
                    "league_code": row["league_code"],
                    "league_name": row["league_name"],
                    "home_team": row["home_team"],
                    "away_team": row["away_team"],
                    "selection": OUTCOME_LABEL[outcome],
                    "selection_name": OUTCOME_NAME[outcome],
                    "odds": round(float(odd), 3),
                    "model_prob": round(float(model_prob), 4),
                    "implied_prob": round(float(implied_prob), 4),
                    "edge": round(float(edge), 4),
                    "expected_roi": round(float(expected_roi), 4),
                    "home_position": int(home_snapshot.get("position", 99)),
                    "away_position": int(away_snapshot.get("position", 99)),
                    "home_last_points_pg": round(float(home_snapshot.get("last_points_pg", 0.0)), 3),
                    "away_last_points_pg": round(float(away_snapshot.get("last_points_pg", 0.0)), 3),
                    "home_injury_impact": round(float(home_snapshot.get("injury_impact", 0.0)), 3),
                    "away_injury_impact": round(float(away_snapshot.get("injury_impact", 0.0)), 3),
                    "home_matches_last7": round(float(home_snapshot.get("total_matches_last7", 0.0)), 2),
                    "away_matches_last7": round(float(away_snapshot.get("total_matches_last7", 0.0)), 2),
                    "home_cards_pg": round(float(home_snapshot.get("cards_pg", 0.0)), 3),
                    "away_cards_pg": round(float(away_snapshot.get("cards_pg", 0.0)), 3),
                    "home_corners_diff_pg": round(float(home_snapshot.get("corners_diff_pg", 0.0)), 3),
                    "away_corners_diff_pg": round(float(away_snapshot.get("corners_diff_pg", 0.0)), 3),
                    "home_goals_against_pg": round(float(home_snapshot.get("goals_against_pg", 0.0)), 3),
                    "away_goals_against_pg": round(float(away_snapshot.get("goals_against_pg", 0.0)), 3),
                    "model_top_factors": explain,
                    "score_momentum": round(float(contributions.get("momentum_gap", 0.0)), 4),
                    "score_home_away": round(float(contributions.get("home_away_gap", 0.0)), 4),
                    "score_injuries": round(float(contributions.get("injury_gap", 0.0)), 4),
                    "score_congestion": round(float(contributions.get("congestion_gap", 0.0)), 4),
                    "score_defense": round(float(contributions.get("defense_gap", 0.0)), 4),
                    "score_forward_goals": round(float(contributions.get("forward_goals_gap", 0.0)), 4),
                    "score_h2h": round(float(contributions.get("h2h_gap", 0.0)), 4),
                    "h2h_matches": int(h2h.get("h2h_matches", 0.0)),
                    "h2h_home_win_rate": round(float(h2h.get("h2h_home_win_rate", 0.0)), 4),
                    "h2h_draw_rate": round(float(h2h.get("h2h_draw_rate", 0.0)), 4),
                    "h2h_away_win_rate": round(float(h2h.get("h2h_away_win_rate", 0.0)), 4),
                    "h2h_goal_diff_pg": round(float(h2h.get("h2h_goal_diff_pg", 0.0)), 4),
                    "important_injured_players": injured_summary,
                    "likely_scorers": scorer_summary,
                    "likely_card_players": card_summary,
                    "match_id": (
                        f"{row['match_date'].date().isoformat()}|{row['league_code']}|"
                        f"{row['home_team']}|{row['away_team']}"
                    ),
                }
            )
    return pd.DataFrame(picks)


def generate_combinations(
    picks: pd.DataFrame,
    combo_sizes: list[int],
    num_combos: int,
    max_picks_pool: int,
    min_combo_ev: float,
) -> pd.DataFrame:
    ranked = picks.sort_values(
        ["expected_roi", "edge", "model_prob"], ascending=False
    ).head(max_picks_pool)

    if ranked.empty:
        return pd.DataFrame()

    records: list[dict[str, object]] = []
    for size in combo_sizes:
        if len(ranked) < size:
            continue

        for combo in itertools.combinations(ranked.to_dict("records"), size):
            match_ids = {entry["match_id"] for entry in combo}
            if len(match_ids) < size:
                continue

            combo_odds = float(np.prod([entry["odds"] for entry in combo]))
            combo_prob = float(np.prod([entry["model_prob"] for entry in combo]))
            combo_ev = combo_prob * combo_odds - 1.0
            if combo_ev < min_combo_ev:
                continue

            selection_text = " | ".join(
                f"{entry['home_team']} vs {entry['away_team']} -> {entry['selection']}"
                for entry in combo
            )
            records.append(
                {
                    "combo_size": size,
                    "legs": selection_text,
                    "combined_odds": round(combo_odds, 3),
                    "hit_probability": round(combo_prob, 4),
                    "expected_roi": round(combo_ev, 4),
                }
            )

    if not records:
        return pd.DataFrame()

    combos = pd.DataFrame(records).sort_values(
        ["expected_roi", "hit_probability"], ascending=False
    )
    per_size = [
        combos.loc[combos["combo_size"] == size].head(num_combos) for size in combo_sizes
    ]
    result = pd.concat(per_size, ignore_index=True) if per_size else pd.DataFrame()
    return result


def main() -> None:
    args = parse_args()
    as_of_date = parse_date(args.as_of_date)
    start_date = parse_date(args.start_date)
    end_date = start_date + timedelta(days=max(args.days_ahead, 0))
    combo_sizes = parse_combo_sizes(args.combo_sizes)

    df = load_data(args.data_file)
    known_results = df["result_ft"].isin(RESULT_VALUES)
    historical = df.loc[known_results & (df["match_date"] < as_of_date)].copy()
    if args.include_completed_fixtures:
        fixtures = df.loc[
            (df["match_date"] >= start_date) & (df["match_date"] <= end_date)
        ].copy()
    else:
        fixtures = df.loc[
            (~known_results)
            & (df["match_date"] >= start_date)
            & (df["match_date"] <= end_date)
        ].copy()

    if historical.empty:
        raise RuntimeError("No historical matches with known results before as-of-date.")
    if fixtures.empty:
        mode = "fixtures" if args.include_completed_fixtures else "upcoming fixtures"
        print(
            f"No {mode} found in range {start_date.date().isoformat()} to {end_date.date().isoformat()}."
        )
        return
    if args.include_completed_fixtures and as_of_date >= start_date:
        print(
            "Warning: as-of-date is on/after start-date, which may cause data leakage in backtest/demo mode."
        )

    injuries_df = _read_optional_csv(args.injuries_file, required_cols=[])
    contrib_df = _read_optional_csv(args.player_contrib_file, required_cols=[])
    other_comp_df = _read_optional_csv(args.other_competitions_file, required_cols=[])

    priors = league_priors(historical)
    snapshot = build_team_snapshot(
        historical=historical,
        as_of_date=as_of_date,
        momentum_window=max(args.momentum_window, 1),
        injuries_df=injuries_df,
        player_contrib_df=contrib_df,
        other_comp_df=other_comp_df,
    )
    picks = build_pick_table(
        fixtures=fixtures,
        snapshot=snapshot,
        priors=priors,
        historical=historical,
        as_of_date=as_of_date,
        h2h_years=max(args.h2h_years, 1),
        odds_source=args.odds_source,
        injuries_df=injuries_df,
        contrib_df=contrib_df,
    )

    if picks.empty:
        print("No picks were generated because fixtures had missing/invalid odds.")
        return

    filtered_picks = picks.loc[
        (picks["model_prob"] >= args.min_pick_prob)
        & (picks["expected_roi"] >= args.min_pick_ev)
    ].sort_values(["expected_roi", "edge", "model_prob"], ascending=False)

    if filtered_picks.empty:
        print("No picks passed the configured thresholds.")
        return

    combos = generate_combinations(
        picks=filtered_picks,
        combo_sizes=combo_sizes,
        num_combos=args.num_combos,
        max_picks_pool=args.max_picks_pool,
        min_combo_ev=args.min_combo_ev,
    )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    window = f"{start_date.date().isoformat()}_to_{end_date.date().isoformat()}"
    picks_path = args.output_dir / f"bet_picks_{window}.csv"
    combos_path = args.output_dir / f"bet_combos_{window}.csv"

    filtered_picks.to_csv(picks_path, index=False)
    if combos.empty:
        print("No combinations passed the configured thresholds.")
    else:
        combos.to_csv(combos_path, index=False)

    print("\nSaved outputs:")
    print(f"- Picks: {picks_path} ({len(filtered_picks)} rows)")
    if combos.empty:
        print("- Combos: none generated")
    else:
        print(f"- Combos: {combos_path} ({len(combos)} rows)")

    preview_cols = [
        "match_date",
        "league_name",
        "home_team",
        "away_team",
        "selection",
        "odds",
        "model_prob",
        "expected_roi",
        "home_position",
        "away_position",
        "model_top_factors",
    ]
    preview = filtered_picks.head(10)[preview_cols]
    print("\nTop picks preview:")
    print(preview.to_string(index=False))

    print("\nNote: This model is heuristic. Treat outputs as decision support, not guaranteed profit.")


if __name__ == "__main__":
    main()
